version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: pg_api_users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - "5432:5432"
    volumes: 
      - pg_data:/var/lib/postgresql
    networks:
      - default

  app: 
    build: .
    user: node:node
    container_name: api-users-nestjs
    depends_on: 
      - db
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - default
    command: "npm run start:dev"
networks:
  default: 
volumes:
  pg_data:
    driver: local