version: '3.9'
services:
  db:
    image: postgres
    container_name: pg_api_users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - default

  app: 
    build: .
    user: node:node
    container_name: api-users-nestjs
    depends_on: 
      - db
    ports:
      - "5000:3000"
    volumes:
      - ./:/app
    networks:
      - default
    command: "npm run start:dev"
networks:
  default: 
    driver: bridge
volumes:
  postgresdata:
    driver: local